#!/usr/bin/env python
# This program setups the ~/.liszt directory.

import os
import shutil
import ConfigParser

path = os.path.expanduser('~/.liszt/')

if os.access(path, os.F_OK):
    # Get rid of the previously created directory.
    try:
        shutil.rmtre(path)
    except OSError:
        print "Error : Unable to remove " + path
        sys.exit(-1)

    os.mkdir(path)
    os.chdir(path)
else:
    os.mkdir(path)
    os.chdir(path)
    os.mkdir("delayed")
    os.mkdir("cached")
    os.system("echo [] > cached/lists_list")

config = ConfigParser.RawConfigParser()

username = raw_input("Please enter your username : ").strip()
password = raw_input("Please enter your password : ").strip()

config.add_section('Credentials')
config.set('Credentials', 'password', password)
config.set('Credentials', 'username', username)

try:
    conffd =  open(path + "config", 'w+')
except IOError:
    print "Unable to open configuration file for writing"
    sys.exit(-1)

config.write(conffd)

print "\nThe configuration file has been created. It's time to create lists !"
